
openapi: 3.0.0
info:
  title: Cochrane CENTRAL Search API
  version: "1.0"
servers:
  - url: https://api.cochrane.org/central
paths:
  /studies/search:
    get:
      summary: Rechercher des études dans Cochrane CENTRAL
      parameters:
        - in: query
          name: q
          required: true
          schema: { type: string }
        - in: query
          name: limit
          schema: { type: integer, default: 5 }
      responses:
        "200":
          description: Résumés des études pertinentes
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
security:
  - BearerAuth: []
